### ISSUE TITLE
ResourceManager::cluster_nodes

### ISSUE THREAD

**Issue by jefimm** [toidi/hadoop-yarn-api-python-client#8] opened 2017-01-23 14:21 UTC
ResourceManager::cluster_nodes does not support filtering nodes by state and healthy as the underlying API does not support filtering

**Comment by dimon222** [comment] 2019-06-02 00:29
The API changed several times, so I think it is true to some extend.

Latest version of Hadoop currently supports only one parameter `states`, and it even its name doesn't match the one we have.
https://hadoop.apache.org/docs/current/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html#Cluster_Nodes_API

However as of version 2.7.3, it will worked with state/healthy parameters.
https://hadoop.apache.org/docs/r2.7.3/hadoop-yarn/hadoop-yarn-site/ResourceManagerRest.html

I'm not exactly sure what would be the best approach for this. Supporting two different APIs with different methods? (aka additional `_legacy` method, and change current to follow latest Hadoop version APIs)

**Comment by dimon222** [comment] 2019-06-06 20:16
@kevin-bates @lresende any suggestions how to handle updated APIs? Are we keeping stuff compliant only to latest YARN stable version? If so, this mentioned API has to be updated

**Comment by kevin-bates** [comment] 2019-06-06 21:11
Not sure I'm up on the various Hadoop versions.  However, `0.3.4` is DOA on my system with the following error:
```
[W 2019-06-06 13:37:48.524 EnterpriseGatewayApp] Query for kernel ID '609c46bb-c98a-41b1-a334-d9a748491348' failed with exception: <class 'TypeError'> - 'request() got an unexpected keyword argument 'startedTimeBegin''.  Continuing...
```
This PR (https://github.com/toidi/hadoop-yarn-api-python-client/pull/31) adjusted the parameters to the `request()` call.  The parameters (https://github.com/toidi/hadoop-yarn-api-python-client/blob/master/yarn_api_client/resource_manager.py#L125-L134) appear YARN related, while this issue is more about the `request()` method itself - so I'm inclined to think this is a bug.

@dimon222 - do you have any ideas?

**Comment by kevin-bates** [comment] 2019-06-06 21:38
I think the issue is that the calls in resource_manager that take `**params` should instead take `params=params`.  Then these will appear on the `requests()` call as the `params` keyword - which then gets passed along to YARN.

Will test this now (sorry for the diversion here).

**Comment by kevin-bates** [comment] 2019-09-19 20:48
Closing via #44

**Closed by kevin-bates** 2019-09-19 20:48 UTC
